=== elesto-dao/elesto/x/credential/keeper/testdata/dummy.schema.json
{"$schema":"http://json-schema.org/draft-07/schema#","$id":"https://beta.api.schemas.serto.id/v1/public/simple/1.0/json-schema.json","$metadata":{"slug":"dummy","version":"1.0","icon":"ðŸ…¢","discoverable":false,"uris":{"jsonLdContextPlus":"https://beta.api.schemas.serto.id/v1/public/simple/1.0/ld-context-plus.json","jsonLdContext":"https://beta.api.schemas.serto.id/v1/public/simple/1.0/ld-context.json","jsonSchema":"https://beta.api.schemas.serto.id/v1/public/simple/1.0/json-schema.json"}},"title":"Dummy","description":"A simple credential definition used for testing","type":"object","required":["@context","type","issuer","issuanceDate","credentialSubject"],"properties":{"@context":{"type":["string","array","object"]},"id":{"type":"string","format":"uri"},"type":{"type":["string","array"],"items":{"type":"string"}},"issuer":{"type":["string","object"],"format":"uri","required":["id"],"properties":{"id":{"type":"string","format":"uri"}}},"issuanceDate":{"type":"string","format":"date-time"},"expirationDate":{"type":"string","format":"date-time"},"credentialSubject":{"type":"object","required":["id"],"properties":{"id":{"title":"Credential Subject ID","type":"string","format":"uri"},"name":{"title":"Name","description":"The name","type":"string"},"age":{"title":"Age","description":"The Age","type":"string"}}},"credentialSchema":{"type":"object","required":["id","type"],"properties":{"id":{"type":"string","format":"uri"},"type":{"type":"string"}}}}}

=== elesto-dao/elesto/x/credential/simulation/testdata/dummy.credential.json
{"@context":["https://www.w3.org/2018/credentials/v1","https://resolver.cc/context/did:cosmos:elesto:dummy"],"id":"https://test.xyz/credential/1","type":["VerifiableCredential","DummyCredential"],"issuer":"did:cosmos:key:elesto17t8t3t6a6vpgk69perfyq930593sa8dnfl98mr","issuanceDate":"2022-06-02T14:13:00Z","credentialSubject":{"age":"42","id":"did:cosmos:key:elesto17t8t3t6a6vpgk69perfyq930593sa8dnfl98mr","name":"Arthur Dent"}}
